//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbInventEntities : DbContext
    {
        public dbInventEntities()
            : base("name=dbInventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tBodegas> tBodegas { get; set; }
        public virtual DbSet<tDepartamentos> tDepartamentos { get; set; }
        public virtual DbSet<tProductos> tProductos { get; set; }
        public virtual DbSet<tProductosCostos> tProductosCostos { get; set; }
        public virtual DbSet<tProductosExistencia> tProductosExistencia { get; set; }
        public virtual DbSet<tProductosInventario> tProductosInventario { get; set; }
        public virtual DbSet<tProveedores> tProveedores { get; set; }
        public virtual DbSet<tProveedoresCuentas> tProveedoresCuentas { get; set; }
    }
}
