//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductos
    {
        public string CodProducto { get; set; }
        public string Descripcion { get; set; }
        public string UnidadMedida { get; set; }
        public decimal PrecioMN { get; set; }
        public Nullable<decimal> PrecioDolar { get; set; }
        public Nullable<decimal> CantidadMinima { get; set; }
        public Nullable<decimal> CantidadMaxima { get; set; }
        public string CodigoSAC { get; set; }
        public string ClasificacionValor { get; set; }
        public string ClasificacionMovimiento { get; set; }
        public Nullable<int> CodSeccion { get; set; }
        public Nullable<int> CodDepartamento { get; set; }
        public Nullable<int> CodFamilia { get; set; }
        public string Ubicacion { get; set; }
    }
}
