//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductosExistencia
    {
        public int idExistencia { get; set; }
        public string CodProducto { get; set; }
        public string CodBodega { get; set; }
        public string Ubicacion { get; set; }
        public decimal Existencia { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
