//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductosInventario
    {
        public string CodBodega { get; set; }
        public string CodProducto { get; set; }
        public decimal ExistenciaActual { get; set; }
        public decimal ExistenciaDisponible { get; set; }
        public Nullable<System.DateTime> FechaUltimoMovimiento { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> NumeroDocumento { get; set; }
    }
}
