//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProductosCostos
    {
        public int idSecuencia { get; set; }
        public string CodProducto { get; set; }
        public decimal ExistenciaActual { get; set; }
        public decimal ExistenciaDisponible { get; set; }
        public decimal CostoUltimaCompraMN { get; set; }
        public decimal CostoUltimaCompraUS { get; set; }
        public decimal TasadeCambioCompra { get; set; }
        public Nullable<System.DateTime> UltimaFechaCompra { get; set; }
        public decimal CostoPromedioMN { get; set; }
        public decimal CostoPromedioUS { get; set; }
        public Nullable<System.DateTime> UltimaFechaPromedio { get; set; }
        public string AgregadoPor { get; set; }
        public Nullable<System.DateTime> AgregadoEl { get; set; }
        public string AgregadoIP { get; set; }
        public string ActualizadoPor { get; set; }
        public Nullable<System.DateTime> ActualizadoEL { get; set; }
        public string ActualizadoIP { get; set; }
    }
}
