//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProveedoresCuentas
    {
        public int idProveedorCuenta { get; set; }
        public int idProveedor { get; set; }
        public string CodBanco { get; set; }
        public string Cuenta { get; set; }
        public string NombreCuenta { get; set; }
        public string Referencia { get; set; }
        public string Instrucciones { get; set; }
        public bool deleted { get; set; }
    }
}
