//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProveedores
    {
        public int idProveedor { get; set; }
        public string CodigoProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string NumeroTributario { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string TipoProveedor { get; set; }
        public string ContactoNombre { get; set; }
        public string ContactoEmail { get; set; }
        public string ContactoTelefono { get; set; }
        public int IdCondicion { get; set; }
        public System.DateTime AgregadoEl { get; set; }
        public string AgregadoPor { get; set; }
        public System.DateTime ModificadoEl { get; set; }
        public string ModificadoPor { get; set; }
        public string Status { get; set; }
    }
}
